on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install -U pip wheel
      - run: cat requirements.txt | xargs -n 1 pip install || exit 0
      - run: pip install .
      - run: python cute.py test
